name: CI - Pull Requests

on:
  pull_request:
    branches: [dev, release, pprod, prod]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test -- --coverage
      - run: ls -al coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  codecov:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.3.0
        with:
          name: coverage-report
      - uses: codecov/codecov-action@v4
        # token: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./**/*.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
